"""initial schema: transactions, match records, discrepancy taxonomy, trust scores, audit log

Hand-authored rather than autogenerated (ADR-0011): constraint names, index choices and
seed data here are deliberate, and a migration nobody read is a migration nobody can trust.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-04
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# The discrepancy taxonomy is reference data, not fixtures: the matching engine and the
# trust layer both key off these codes, so a freshly migrated database is only usable if
# they are present. Seeded here rather than in a separate script for exactly that reason.
#
# (code, display_name, description, severity, tolerance_minor, auto_resolvable)
CATEGORIES: list[tuple[str, str, str, str, int, bool]] = [
    (
        "ROUNDING_DIFFERENCE",
        "Rounding difference",
        "Sub-rupee delta consistent with rounding at one of the three sources.",
        "LOW",
        100,  # up to 1.00 INR
        True,
    ),
    (
        "TIMING_DIFFERENCE",
        "Timing difference",
        "All three legs agree on amount; the bank leg lands in a later settlement window.",
        "LOW",
        0,
        True,
    ),
    (
        "FEE_DEDUCTION",
        "Processor fee deduction",
        "Bank credit is short by a processor fee that the ledger records gross.",
        "MEDIUM",
        0,
        True,
    ),
    (
        "TAX_WITHHOLDING",
        "Tax withheld at source",
        "Delta corresponds to tax withheld by the processor before settlement.",
        "MEDIUM",
        0,
        False,
    ),
    (
        "FX_CONVERSION_DRIFT",
        "FX conversion drift",
        "Cross-currency settlement converted at a rate differing from the ledger rate.",
        "MEDIUM",
        500,  # up to 5.00 INR
        False,
    ),
    (
        "REFERENCE_MISMATCH",
        "Reference mismatch",
        "Amounts and dates align but the UTR/RRN differs or is truncated between sources.",
        "MEDIUM",
        0,
        False,
    ),
    (
        "REFUND_OFFSET",
        "Refund offset",
        "Settlement is net of a refund that the ledger books as a separate entry.",
        "MEDIUM",
        0,
        False,
    ),
    (
        "AMOUNT_MISMATCH",
        "Amount mismatch",
        "Legs disagree on amount beyond any configured tolerance, cause unexplained.",
        "HIGH",
        0,
        False,
    ),
    (
        "DUPLICATE_ENTRY",
        "Duplicate entry",
        "The same payment appears more than once within a single source.",
        "HIGH",
        0,
        False,
    ),
    (
        "MISSING_IN_LEDGER",
        "Missing in internal ledger",
        "Processor and bank agree; the internal ledger has no corresponding entry.",
        "HIGH",
        0,
        False,
    ),
    (
        "MISSING_IN_PSP",
        "Missing in processor settlement",
        "Bank and ledger agree; the processor settlement report has no matching row.",
        "HIGH",
        0,
        False,
    ),
    (
        "CHARGEBACK_ADJUSTMENT",
        "Chargeback adjustment",
        "Settlement is reduced by a chargeback or dispute adjustment.",
        "HIGH",
        0,
        False,
    ),
    (
        "MISSING_IN_BANK",
        "Missing in bank statement",
        "Processor and ledger agree, but no money reached the bank. Treated as critical: "
        "this is the shape of both a settlement failure and a misdirected payout.",
        "CRITICAL",
        0,
        False,
    ),
    (
        "UNCLASSIFIED",
        "Unclassified discrepancy",
        "No deterministic rule matched. Never auto-resolvable by construction.",
        "HIGH",
        0,
        False,
    ),
]

# Cold-start trust posture. Every category starts at score 0 with sample_size 0, which the
# gate reads as "no evidence" rather than "bad". Thresholds are stricter for the severities
# where being wrong is expensive; min_sample_size is the floor below which the score is not
# treated as evidence at all.
THRESHOLDS_BY_SEVERITY: dict[str, tuple[float, float, int]] = {
    # severity: (auto_apply_threshold, review_threshold, min_sample_size)
    "LOW": (0.85, 0.50, 30),
    "MEDIUM": (0.90, 0.60, 50),
    "HIGH": (0.95, 0.70, 100),
    "CRITICAL": (0.99, 0.80, 250),
}


def upgrade() -> None:
    # --- discrepancy_categories ---------------------------------------------------
    # Created first: both trust_scores and match_records reference it.
    op.create_table(
        "discrepancy_categories",
        sa.Column("code", sa.String(64), nullable=False),
        sa.Column("display_name", sa.String(128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(16), nullable=False),
        sa.Column("tolerance_minor", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("auto_resolvable", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("code", name="pk_discrepancy_categories"),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name="severity",
        ),
        sa.CheckConstraint(
            "tolerance_minor >= 0",
            name="tolerance_non_negative",
        ),
    )

    # --- transactions -------------------------------------------------------------
    op.create_table(
        "transactions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source", sa.String(32), nullable=False),
        sa.Column("external_id", sa.String(128), nullable=False),
        sa.Column("counterparty_ref", sa.String(128), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False),
        sa.Column("direction", sa.String(16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="UNMATCHED"),
        sa.Column("raw", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name="pk_transactions"),
        # Makes re-ingesting the same settlement file a conflict, not a duplicate.
        sa.UniqueConstraint("source", "external_id", name="uq_transactions_source_external_id"),
        sa.CheckConstraint(
            "source IN ('PSP_SETTLEMENT', 'BANK_STATEMENT', 'INTERNAL_LEDGER')",
            name="source",
        ),
        sa.CheckConstraint("direction IN ('CREDIT', 'DEBIT')", name="direction"),
        sa.CheckConstraint(
            "status IN ('UNMATCHED', 'MATCHED', 'EXCEPTION')", name="status"
        ),
    )
    op.create_index("ix_transactions_counterparty_ref", "transactions", ["counterparty_ref"])
    op.create_index(
        "ix_transactions_source_occurred_at", "transactions", ["source", "occurred_at"]
    )
    op.create_index("ix_transactions_status", "transactions", ["status"])
    # The Phase 2 amount+date fallback pass scans this; without it that pass is a seq scan.
    op.create_index(
        "ix_transactions_amount_minor_occurred_at",
        "transactions",
        ["amount_minor", "occurred_at"],
    )

    # --- match_records --------------------------------------------------------------
    op.create_table(
        "match_records",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("match_key", sa.String(128), nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("strategy", sa.String(32), nullable=False),
        sa.Column("confidence", sa.Numeric(5, 4), nullable=False),
        sa.Column("psp_transaction_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("bank_transaction_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("ledger_transaction_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("amount_delta_minor", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("category_code", sa.String(64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name="pk_match_records"),
        sa.ForeignKeyConstraint(
            ["psp_transaction_id"],
            ["transactions.id"],
            name="fk_match_records_psp_transaction_id_transactions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["transactions.id"],
            name="fk_match_records_bank_transaction_id_transactions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ledger_transaction_id"],
            ["transactions.id"],
            name="fk_match_records_ledger_transaction_id_transactions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["discrepancy_categories.code"],
            name="fk_match_records_category_code_discrepancy_categories",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="confidence_in_range"
        ),
        # A match with no legs is meaningless and would otherwise insert cleanly.
        sa.CheckConstraint(
            "num_nonnulls(psp_transaction_id, bank_transaction_id, ledger_transaction_id) >= 1",
            name="at_least_one_leg",
        ),
        sa.CheckConstraint(
            "status IN ('FULL', 'PARTIAL', 'BROKEN')", name="status"
        ),
        sa.CheckConstraint(
            "strategy IN ('EXACT_REFERENCE', 'REFERENCE_AMOUNT_TOLERANCE', "
            "'AMOUNT_DATE_WINDOW', 'MANUAL')",
            name="strategy",
        ),
    )
    # A transaction belongs to at most one match. Postgres permits unlimited NULLs under a
    # UNIQUE index, which is exactly the semantics an optional leg needs.
    op.create_index(
        "uq_match_records_psp_transaction_id",
        "match_records",
        ["psp_transaction_id"],
        unique=True,
    )
    op.create_index(
        "uq_match_records_bank_transaction_id",
        "match_records",
        ["bank_transaction_id"],
        unique=True,
    )
    op.create_index(
        "uq_match_records_ledger_transaction_id",
        "match_records",
        ["ledger_transaction_id"],
        unique=True,
    )
    op.create_index("ix_match_records_match_key", "match_records", ["match_key"])
    op.create_index("ix_match_records_status", "match_records", ["status"])

    # --- trust_scores ---------------------------------------------------------------
    op.create_table(
        "trust_scores",
        sa.Column("category_code", sa.String(64), nullable=False),
        sa.Column("score", sa.Numeric(5, 4), nullable=False, server_default="0"),
        sa.Column("sample_size", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("correct_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("auto_apply_threshold", sa.Numeric(5, 4), nullable=False),
        sa.Column("review_threshold", sa.Numeric(5, 4), nullable=False),
        sa.Column("min_sample_size", sa.Integer(), nullable=False, server_default="50"),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("category_code", name="pk_trust_scores"),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["discrepancy_categories.code"],
            name="fk_trust_scores_category_code_discrepancy_categories",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="score_in_range"),
        sa.CheckConstraint("sample_size >= 0", name="sample_size_non_negative"),
        sa.CheckConstraint(
            "correct_count >= 0 AND correct_count <= sample_size",
            name="correct_count_within_sample",
        ),
        sa.CheckConstraint("min_sample_size >= 1", name="min_sample_size_positive"),
        sa.CheckConstraint(
            "auto_apply_threshold >= 0 AND auto_apply_threshold <= 1",
            name="auto_apply_threshold_in_range",
        ),
        # Without this, review_threshold >= auto_apply_threshold would leave no band in
        # which a human is asked -- the gate would be silently incoherent.
        sa.CheckConstraint(
            "review_threshold >= 0 AND review_threshold < auto_apply_threshold",
            name="review_below_auto_apply",
        ),
    )

    # --- audit_events ---------------------------------------------------------------
    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("actor_type", sa.String(16), nullable=False),
        sa.Column("actor_id", sa.String(128), nullable=True),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("entity_type", sa.String(64), nullable=False),
        sa.Column("entity_id", sa.String(128), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.PrimaryKeyConstraint("id", name="pk_audit_events"),
        sa.CheckConstraint(
            "actor_type IN ('SYSTEM', 'AGENT', 'USER')", name="actor_type"
        ),
    )
    op.create_index(
        "ix_audit_events_entity_type_entity_id", "audit_events", ["entity_type", "entity_id"]
    )
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"])
    op.create_index("ix_audit_events_actor_type", "audit_events", ["actor_type"])

    _seed_reference_data()


def _seed_reference_data() -> None:
    """Insert the discrepancy taxonomy and its cold-start trust rows."""
    categories_table = sa.table(
        "discrepancy_categories",
        sa.column("code", sa.String),
        sa.column("display_name", sa.String),
        sa.column("description", sa.Text),
        sa.column("severity", sa.String),
        sa.column("tolerance_minor", sa.BigInteger),
        sa.column("auto_resolvable", sa.Boolean),
    )
    op.bulk_insert(
        categories_table,
        [
            {
                "code": code,
                "display_name": display_name,
                "description": description,
                "severity": severity,
                "tolerance_minor": tolerance,
                "auto_resolvable": auto_resolvable,
            }
            for code, display_name, description, severity, tolerance, auto_resolvable in CATEGORIES
        ],
    )

    trust_table = sa.table(
        "trust_scores",
        sa.column("category_code", sa.String),
        sa.column("score", sa.Numeric),
        sa.column("sample_size", sa.Integer),
        sa.column("correct_count", sa.Integer),
        sa.column("auto_apply_threshold", sa.Numeric),
        sa.column("review_threshold", sa.Numeric),
        sa.column("min_sample_size", sa.Integer),
    )
    op.bulk_insert(
        trust_table,
        [
            {
                "category_code": code,
                # Cold start: zero observations. The gate reads this as "no evidence",
                # never as "trustworthy" and never as "bad".
                "score": 0,
                "sample_size": 0,
                "correct_count": 0,
                "auto_apply_threshold": THRESHOLDS_BY_SEVERITY[severity][0],
                "review_threshold": THRESHOLDS_BY_SEVERITY[severity][1],
                "min_sample_size": THRESHOLDS_BY_SEVERITY[severity][2],
            }
            for code, _display_name, _description, severity, _tolerance, _auto in CATEGORIES
        ],
    )


def downgrade() -> None:
    # Reverse creation order so foreign keys drop cleanly.
    op.drop_table("audit_events")
    op.drop_table("trust_scores")
    op.drop_table("match_records")
    op.drop_table("transactions")
    op.drop_table("discrepancy_categories")
